/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jcadastropendentes;

import Classes.*;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author lcbenfic
 */
public class jFAderenciaMeta extends javax.swing.JDialog {

    /**
     * Creates new form jFAderenciaMeta
     */
    public jFAderenciaMeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        salvarjButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        alterarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        limparjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        calculaAderenciajButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeAderenciajTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pergundaUmjLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        perguntaDoisjLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        perguntaTresjLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        perguntaQuatrojLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        perguntaUmjTextField = new javax.swing.JTextField();
        perguntaDoisjTextField = new javax.swing.JTextField();
        perguntatresjTextField = new javax.swing.JTextField();
        totaljTextField = new javax.swing.JTextField();
        aderenciajTextField = new javax.swing.JTextField();
        perguntaQuatrojTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        datajFormattedTextField = new javax.swing.JFormattedTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        credenciadojTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buscarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar.png"))); // NOI18N
        buscarjButton.setText("Buscar");
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new2.png"))); // NOI18N
        novojButton.setText("Novo");
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);

        editarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        editarjButton.setText("Editar");
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);
        jToolBar1.add(jSeparator3);

        salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        salvarjButton.setText("Salvar");
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);
        jToolBar1.add(jSeparator2);

        alterarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save2.png"))); // NOI18N
        alterarjButton.setText("Alterar");
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);

        excluirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        excluirjButton.setText("Excluir");
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(excluirjButton);
        jToolBar1.add(jSeparator1);

        limparjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clear.png"))); // NOI18N
        limparjButton.setText("Limpar");
        limparjButton.setFocusable(false);
        limparjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limparjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(limparjButton);

        sairjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit.png"))); // NOI18N
        sairjButton.setText("Sair");
        sairjButton.setFocusable(false);
        sairjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairjButton);

        calculaAderenciajButton.setContentAreaFilled(false);
        calculaAderenciajButton.setFocusable(false);
        calculaAderenciajButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calculaAderenciajButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        calculaAderenciajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaAderenciajButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(calculaAderenciajButton);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gradeAderenciajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id#", "Item 1", "Item 2", "Item 3", "Item 4", "Total", "Aderencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeAderenciajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeAderenciajTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeAderenciajTable);
        gradeAderenciajTable.getColumnModel().getColumn(0).setResizable(false);
        gradeAderenciajTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradeAderenciajTable.getColumnModel().getColumn(1).setResizable(false);
        gradeAderenciajTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        gradeAderenciajTable.getColumnModel().getColumn(2).setResizable(false);
        gradeAderenciajTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        gradeAderenciajTable.getColumnModel().getColumn(3).setResizable(false);
        gradeAderenciajTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        gradeAderenciajTable.getColumnModel().getColumn(4).setResizable(false);
        gradeAderenciajTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        gradeAderenciajTable.getColumnModel().getColumn(5).setResizable(false);
        gradeAderenciajTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        gradeAderenciajTable.getColumnModel().getColumn(6).setResizable(false);
        gradeAderenciajTable.getColumnModel().getColumn(6).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pergundaUmjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOTAL");

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADERENCIA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(pergundaUmjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perguntaDoisjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perguntaTresjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perguntaQuatrojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pergundaUmjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(perguntaDoisjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(perguntaQuatrojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(perguntaTresjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        perguntaUmjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        perguntaUmjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                perguntaUmjTextFieldFocusLost(evt);
            }
        });
        perguntaUmjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perguntaUmjTextFieldKeyTyped(evt);
            }
        });

        perguntaDoisjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        perguntaDoisjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                perguntaDoisjTextFieldFocusLost(evt);
            }
        });
        perguntaDoisjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perguntaDoisjTextFieldKeyTyped(evt);
            }
        });

        perguntatresjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        perguntatresjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                perguntatresjTextFieldFocusLost(evt);
            }
        });
        perguntatresjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perguntatresjTextFieldKeyTyped(evt);
            }
        });

        totaljTextField.setEditable(false);
        totaljTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totaljTextField.setFocusable(false);

        aderenciajTextField.setEditable(false);
        aderenciajTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aderenciajTextField.setFocusable(false);

        perguntaQuatrojTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perguntaUmjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perguntaDoisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(perguntatresjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perguntaQuatrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totaljTextField)
                .addGap(18, 18, 18)
                .addComponent(aderenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perguntaUmjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perguntaDoisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perguntatresjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aderenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perguntaQuatrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aderência aos processos", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Data:");

        try {
            datajFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Credenciado");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(credenciadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(datajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(credenciadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClassConecta conecta = new ClassConecta();
    
    int item1 = 0;
    int item2 = 0;
    int item3 = 0;
    int item4 = 0;
    int total;
    
    
    String recebe_credenciado;
    int recebe_codigo_crecenciado;
    int recebe_codigo_regional;
    int recebe_codigo_lista;
    
    int codigo_click_aderencia;
    
    
    public void getGradeAderenciaAosProcessos() throws ParseException{
       //Consultar Pessoas
        AderenciaAMeta oAderenciaAMeta = new AderenciaAMeta();

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Id#", "Item 1", "Item 2", "Item 3", "Item 4", "Total", "Aderencia"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeAderenciajTable.setModel(modeloTabela);
        gradeAderenciajTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradeAderenciajTable.getColumnModel().getColumn(1).setPreferredWidth(30);
        gradeAderenciajTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        gradeAderenciajTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        gradeAderenciajTable.getColumnModel().getColumn(4).setPreferredWidth(30);
        gradeAderenciajTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        gradeAderenciajTable.getColumnModel().getColumn(6).setPreferredWidth(150);
        
        
        
//        TableColumn coluna = gradeAderenciajTable.getColumn(5);
        

try {
            oAderenciaAMeta.setCodigo_lista_relatorio(recebe_codigo_lista);
            oAderenciaAMeta.setCodigo_pessoa_campo_credenciado(recebe_codigo_crecenciado);
            oAderenciaAMeta.setCodigo_regional(recebe_codigo_regional);
            resultSet = oAderenciaAMeta.getConsultar(conecta);
            if (resultSet.getRow() == 1){
             resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(PessoasCampo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {    
                

                modeloTabela.addRow(new String[]{
                    Funcoes.getCodigoFormat(resultSet.getInt("CODIGO_ADERENCIA_AOS_PROCEDIMENTOS")),
                    resultSet.getString("PERGUNTA1"),
                    resultSet.getString("PERGUNTA2"),
                    resultSet.getString("PERGUNTA3"),
                    resultSet.getString("PERGUNTA4"),
                    resultSet.getString("VALOR").concat("%"),
                    resultSet.getString("ADERENCIA")
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(PessoasCampo.class.getName()).log(Level.SEVERE, null, ex);
        }

           }
    
    
    public void getFieldAderencia(int codigo_click_aderencia) throws ParseException{
        //Buscar contato
        AderenciaAMeta oAderenciaAMeta = new AderenciaAMeta();
        ResultSet rs;
        

        try {
            oAderenciaAMeta.setCodigo_aderencia_aos_processos(codigo_click_aderencia);
            rs = oAderenciaAMeta.getConsultar(conecta);
            rs.next();

            //Pegar campos           
            perguntaUmjTextField.setText(rs.getString("PERGUNTA1"));
            perguntaDoisjTextField.setText(rs.getString("PERGUNTA2"));
            perguntatresjTextField.setText(rs.getString("PERGUNTA3"));
            perguntaQuatrojTextField.setText(rs.getString("PERGUNTA4"));
            datajFormattedTextField.setValue(Funcoes.getDataFormat(rs.getDate("DATA")));
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPendentes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao preencher os campos\n"+ex, "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pergundaUmjLabel.setText("<html><center>"
                + "TODAS AS OSs NÃO<br> "
                + "FINALIZADAS NO DIA<br> "
                + "ANTERIOR, OS CLIENTES<br> "
                + "RECEBERAM CONTATO?</center></html>");
        
        perguntaDoisjLabel.setText("<html><center>"
                + "OSs AGENDADAS<br> PARA O DIA ESTÃO<br> ALOCADAS PARA OS<br> TÉCNICOS?"
                + "</center></html>");
        
        perguntaTresjLabel.setText("<html><center>"
                + "OSs COM CONTADOR<br> DE VISITAS >3, ESTÃO<br> COM TÉCNICOS COM<br> NIVEL >3."
                + "</center></html>");
        
        perguntaQuatrojLabel.setText("<html><center>"
                + "TODOS OS ALERTAS<br> ESTÃO DIRECIONADOS<br> PARA ANTENDIMENTO?"
                + "</center></html>");
        totaljTextField.setText("0%");
        
        novojButton.setEnabled(true);
        editarjButton.setEnabled(false);
        salvarjButton.setEnabled(false);
        alterarjButton.setEnabled(false);
        excluirjButton.setEnabled(false);
        
        try {
            ClassConecta.getConectaContatosTorreDB();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro aco conectar com o banco de dados\n"+e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        try {
            datajFormattedTextField.setText(Funcoes.getNowBR());
        } catch (Exception e) {
        }
        credenciadojTextField.setText(recebe_credenciado);
        
        
        buscarjButtonActionPerformed(null);
        
        int somaLinhas = gradeAderenciajTable.getModel().getRowCount();
        if(somaLinhas == 5){
            novojButton.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void perguntaUmjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perguntaUmjTextFieldKeyTyped
        // TODO add your handling code here:
        String caracteres="Xx";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_perguntaUmjTextFieldKeyTyped

    private void perguntaDoisjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perguntaDoisjTextFieldKeyTyped
        // TODO add your handling code here:
        String caracteres="Xx";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_perguntaDoisjTextFieldKeyTyped

    private void perguntatresjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perguntatresjTextFieldKeyTyped
        // TODO add your handling code here:
        String caracteres="Xx";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_perguntatresjTextFieldKeyTyped

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    private void calculaAderenciajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaAderenciajButtonActionPerformed
        // TODO add your handling code here:
        if(perguntaUmjTextField.getText().isEmpty()){
            
            item1 = 0;
        }else{
            item1 = 25;
        }
        if(perguntaDoisjTextField.getText().isEmpty()){
            item2 = 0;
        }else{
            item2 = 25;
        }
        if(perguntatresjTextField.getText().isEmpty()){
            item3 = 0;
        }else{
            item3 = 25;
        }
        if(perguntaQuatrojTextField.getText().isEmpty()){
            item4 = 0;
        }else{
            item4 = 25;
        }
        total = item1 + item2 + item3 + item4;
        
        
        System.out.println(item1 + " "+item2+" "+item3+" "+item4+ " valor total "+total);
        System.out.println(total);
        
        totaljTextField.setText(String.valueOf(total) + "%");
        
        Color cor_nao_aderiu = new Color(230,184,183);
        Color cor_fonte_naoAderiu = new Color(192,0,0);
        
        Color cor_fundo_aderiuParc = new Color(255,255,153);
        Color cor_fonte_Aderiuparc = new Color(168,145,4);
        
        Color cor_fundo_aderiu = new Color(162,231,157);
        Color cor_fonte_Aderiu = new Color(40,97,25);
        
        switch (totaljTextField.getText()) {
            case "25%":
                aderenciajTextField.setText("NÃO ADERIU");
                aderenciajTextField.setBackground(cor_nao_aderiu);
                aderenciajTextField.setForeground(cor_fonte_naoAderiu);
                break;
                
            case "50%":
            case "75%":
                aderenciajTextField.setText("ADERIU PARCIALMENTE");
                aderenciajTextField.setBackground(cor_fundo_aderiuParc);
                aderenciajTextField.setForeground(cor_fonte_Aderiuparc);
                break;
                
            case "100%":
                aderenciajTextField.setText("ADERIU");
                aderenciajTextField.setBackground(cor_fundo_aderiu);
                aderenciajTextField.setForeground(cor_fonte_Aderiu);
                break;
            
            default:
                aderenciajTextField.setText("NÃO ADERIU");
                aderenciajTextField.setBackground(cor_nao_aderiu);
                aderenciajTextField.setForeground(cor_fonte_naoAderiu);
        }
    }//GEN-LAST:event_calculaAderenciajButtonActionPerformed

    private void perguntaUmjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perguntaUmjTextFieldFocusLost
        // TODO add your handling code here:
        calculaAderenciajButtonActionPerformed(null);
    }//GEN-LAST:event_perguntaUmjTextFieldFocusLost

    private void perguntaDoisjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perguntaDoisjTextFieldFocusLost
        // TODO add your handling code here:
        calculaAderenciajButtonActionPerformed(null);
    }//GEN-LAST:event_perguntaDoisjTextFieldFocusLost

    private void perguntatresjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perguntatresjTextFieldFocusLost
        // TODO add your handling code here:
        calculaAderenciajButtonActionPerformed(null);
    }//GEN-LAST:event_perguntatresjTextFieldFocusLost

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        editarjButton.setEnabled(false);
        buscarjButton.setEnabled(true);
        salvarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(false);
//        int somaLinhas = gradeAderenciajTable.getModel().getRowCount();
//        if(somaLinhas == 5){
//            novojButton.setEnabled(false);
//        }else{
//        novojButton.setEnabled(true);    
//        }
        
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (Exception e) {
        }
        datajFormattedTextField.grabFocus();
        limparjButtonActionPerformed(evt);
    }//GEN-LAST:event_novojButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        AderenciaAMeta oAderenciaAMeta = new AderenciaAMeta();
        
        
        if(recebe_codigo_lista == 0){
          JOptionPane.showMessageDialog(null, "Atenção!\nVolte e clique em uma lista", "mensagem do sistema", JOptionPane.WARNING_MESSAGE);  
        }else if(datajFormattedTextField.getText().equals("  /  /    ")){
            
            JOptionPane.showMessageDialog(null, "Insira uma data", "mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else{
            try {
                salvarjButton.setEnabled(false);
                novojButton.setEnabled(true);
                editarjButton.setEnabled(true);
                excluirjButton.setEnabled(false);
                
                datajFormattedTextField.grabFocus();
                calculaAderenciajButtonActionPerformed(evt);
                
                oAderenciaAMeta.setCodigo_pessoa_campo_credenciado(recebe_codigo_crecenciado);
                oAderenciaAMeta.setCodigo_regional(recebe_codigo_regional);
                oAderenciaAMeta.setCodigo_lista_relatorio(recebe_codigo_lista);
                
                oAderenciaAMeta.setData(Funcoes.getDataFormatBR(datajFormattedTextField.getText()));
                oAderenciaAMeta.setPergunta1(perguntaUmjTextField.getText().toUpperCase());
                oAderenciaAMeta.setPergunta2(perguntaDoisjTextField.getText().toUpperCase());
                oAderenciaAMeta.setPergunta3(perguntatresjTextField.getText().toUpperCase());
                oAderenciaAMeta.setPergunta4(perguntaQuatrojTextField.getText().toUpperCase());
                oAderenciaAMeta.setValor(total);
                oAderenciaAMeta.setAderencia(aderenciajTextField.getText());
                oAderenciaAMeta.setCadastrar();  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao alterar registros\n"+e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
            try {
            getGradeAderenciaAosProcessos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar grade\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
         buscarjButtonActionPerformed(evt);     
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        // TODO add your handling code here:
        try {
            getGradeAderenciaAosProcessos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar grade\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        int somaLinhas = gradeAderenciajTable.getModel().getRowCount();
        if(somaLinhas == 5){
            novojButton.setEnabled(false);
        }else{
        novojButton.setEnabled(true);    
        }
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void gradeAderenciajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeAderenciajTableMouseClicked
        // TODO add your handling code here:
        editarjButton.setEnabled(true);
        codigo_click_aderencia = Integer.parseInt(gradeAderenciajTable.getValueAt(gradeAderenciajTable.getSelectedRow(), 0).toString());
        try {
            getFieldAderencia(codigo_click_aderencia);
        } catch (ParseException ex) {
            Logger.getLogger(PessoasCampo.class.getName()).log(Level.SEVERE, null, ex);
        }
        calculaAderenciajButtonActionPerformed(null);
    }//GEN-LAST:event_gradeAderenciajTableMouseClicked

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        perguntaUmjTextField.setText("");
        perguntaDoisjTextField.setText("");
        perguntatresjTextField.setText("");
        perguntaQuatrojTextField.setText("");
        try {
            datajFormattedTextField.setText(Funcoes.getNowBR());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        AderenciaAMeta oAderenciaAMeta = new AderenciaAMeta();
        
        if(datajFormattedTextField.getText().equals("  /  /    ")){
            
            JOptionPane.showMessageDialog(null, "Insira uma data", "mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else{
            try {
                salvarjButton.setEnabled(false);
                novojButton.setEnabled(true);
                editarjButton.setEnabled(true);
                excluirjButton.setEnabled(false);
                alterarjButton.setEnabled(false);
                
                datajFormattedTextField.grabFocus();
                calculaAderenciajButtonActionPerformed(evt);
                
                oAderenciaAMeta.setCodigo_aderencia_aos_processos(codigo_click_aderencia);
                oAderenciaAMeta.setCodigo_pessoa_campo_credenciado(recebe_codigo_crecenciado);
                oAderenciaAMeta.setCodigo_regional(recebe_codigo_regional);
                oAderenciaAMeta.setCodigo_lista_relatorio(recebe_codigo_lista);
                
                oAderenciaAMeta.setData(Funcoes.getDataFormatBR(datajFormattedTextField.getText()));
                oAderenciaAMeta.setPergunta1(perguntaUmjTextField.getText().toUpperCase());
                oAderenciaAMeta.setPergunta2(perguntaDoisjTextField.getText().toUpperCase());
                oAderenciaAMeta.setPergunta3(perguntatresjTextField.getText().toUpperCase());
                oAderenciaAMeta.setPergunta4(perguntaQuatrojTextField.getText().toUpperCase());
                oAderenciaAMeta.setValor(total);
                oAderenciaAMeta.setAderencia(aderenciajTextField.getText());
                oAderenciaAMeta.setAlterar(conecta);  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao alterar registros\n"+e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
            try {
            getGradeAderenciaAosProcessos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar grade\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
         buscarjButtonActionPerformed(evt);     
        }
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setEnabled(false);
        salvarjButton.setEnabled(false);
        editarjButton.setEnabled(false);
        alterarjButton.setEnabled(true);
        excluirjButton.setEnabled(true);
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPendentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(
                null,
                "Deseja realmente EXCLUIR esse registro?",
                "Confirmação!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (sd != 0) {
            return;
        }
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);
        
        AderenciaAMeta oAderenciaAMeta = new AderenciaAMeta();
        
        oAderenciaAMeta.setCodigo_aderencia_aos_processos(codigo_click_aderencia);
        oAderenciaAMeta.setExcluir(conecta);
        
        try {
            getGradeAderenciaAosProcessos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar grade\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        buscarjButtonActionPerformed(evt);
        limparjButtonActionPerformed(null);
    }//GEN-LAST:event_excluirjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFAderenciaMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFAderenciaMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFAderenciaMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFAderenciaMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new jFAderenciaMeta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aderenciajTextField;
    private javax.swing.JButton alterarjButton;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JButton calculaAderenciajButton;
    private javax.swing.JTextField credenciadojTextField;
    private javax.swing.JFormattedTextField datajFormattedTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTable gradeAderenciajTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JButton novojButton;
    private javax.swing.JLabel pergundaUmjLabel;
    private javax.swing.JLabel perguntaDoisjLabel;
    private javax.swing.JTextField perguntaDoisjTextField;
    private javax.swing.JLabel perguntaQuatrojLabel;
    private javax.swing.JTextField perguntaQuatrojTextField;
    private javax.swing.JLabel perguntaTresjLabel;
    private javax.swing.JTextField perguntaUmjTextField;
    private javax.swing.JTextField perguntatresjTextField;
    private javax.swing.JButton sairjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTextField totaljTextField;
    // End of variables declaration//GEN-END:variables
}
