/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jcadastropendentes;

import Classes.CadastroPendentes;
import Classes.ClassConecta;
import Classes.ExportarExcel;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.title.Title;

/**
 *
 * @author lcbenfic
 */
public class jFDeletaBanco extends javax.swing.JFrame {

    /**
     * Creates new form jFDeletaBanco
     */
    public jFDeletaBanco() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/resources/radio-tower-32.png")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        atualizajButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        apagaRegistrosBancojButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        sairjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradePendentejTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        exportaParaExceljButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalRegistrosjLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalRegistroVencidojLabel = new javax.swing.JLabel();
        TotalPendentesNoPrazojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        atualizajButton.setText("Atualiza");
        atualizajButton.setFocusable(false);
        atualizajButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        atualizajButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        atualizajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizajButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(atualizajButton);
        jToolBar1.add(jSeparator1);

        apagaRegistrosBancojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove-from-database.png"))); // NOI18N
        apagaRegistrosBancojButton.setText("Apaga BD");
        apagaRegistrosBancojButton.setFocusable(false);
        apagaRegistrosBancojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apagaRegistrosBancojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        apagaRegistrosBancojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagaRegistrosBancojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(apagaRegistrosBancojButton);
        jToolBar1.add(jSeparator2);

        sairjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit.png"))); // NOI18N
        sairjButton.setText("Sair");
        sairjButton.setFocusable(false);
        sairjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairjButton);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gradePendentejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Cliente", "Protocolo", "Data abertura", "Regional", "Vencido", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(gradePendentejTable);
        gradePendentejTable.getColumnModel().getColumn(0).setResizable(false);
        gradePendentejTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        gradePendentejTable.getColumnModel().getColumn(1).setResizable(false);
        gradePendentejTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        gradePendentejTable.getColumnModel().getColumn(2).setResizable(false);
        gradePendentejTable.getColumnModel().getColumn(2).setPreferredWidth(60);
        gradePendentejTable.getColumnModel().getColumn(3).setResizable(false);
        gradePendentejTable.getColumnModel().getColumn(3).setPreferredWidth(45);
        gradePendentejTable.getColumnModel().getColumn(4).setResizable(false);
        gradePendentejTable.getColumnModel().getColumn(4).setPreferredWidth(65);
        gradePendentejTable.getColumnModel().getColumn(5).setResizable(false);
        gradePendentejTable.getColumnModel().getColumn(5).setPreferredWidth(10);
        gradePendentejTable.getColumnModel().getColumn(6).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        exportaParaExceljButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/export_excel.png"))); // NOI18N
        exportaParaExceljButton.setText("Exportar para excel");
        exportaParaExceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportaParaExceljButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de registros:");

        jLabel2.setText("Total de pendentes vencidos:");

        jLabel3.setText("Total de pendentes no prazo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalRegistrosjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalRegistroVencidojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPendentesNoPrazojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportaParaExceljButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportaParaExceljButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalRegistrosjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalRegistroVencidojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPendentesNoPrazojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String recebe_usuario_logado;
    
    ClassConecta conecta = new ClassConecta();
    
    public int recebe_controle_botão;
    
    public void getGradePendentes() throws ParseException{
       //Consultar PENDENTES
        CadastroPendentes oCadastroPendentes = new CadastroPendentes();

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Customer", "Cliente", "Protocolo", "Data abertura", "Regional", "Vencido", "Descrição"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradePendentejTable.setModel(modeloTabela);
//        gradePendentejTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradePendentejTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        gradePendentejTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        gradePendentejTable.getColumnModel().getColumn(3).setPreferredWidth(60);
        gradePendentejTable.getColumnModel().getColumn(4).setPreferredWidth(45);
        gradePendentejTable.getColumnModel().getColumn(5).setPreferredWidth(65);
        gradePendentejTable.getColumnModel().getColumn(6).setPreferredWidth(10);

try {
            resultSet = oCadastroPendentes.getConsultar(conecta);
            if (resultSet.getRow() == 1){
             resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(CadastroPendentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
//                    Funcoes.getCodigoFormat(resultSet.getInt("COD_CADASTROS")),
                    resultSet.getString("CUSTOMER"),
                    resultSet.getString("NOME_CLIENTE"),
                    resultSet.getString("PROTOCOLO_ABERTURA"),
                    resultSet.getString("DATA_ABERTURA"),
                    resultSet.getString("REGIONAL"),
                    resultSet.getString("VENCIDO"),
                    resultSet.getString("PROBLEMA")
                });
                
            }

        } catch (SQLException ex) {
            Logger.getLogger(CadastroPendentes.class.getName()).log(Level.SEVERE, null, ex);
        }

           }
    
    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        
       this.dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        atualizajButton.setVisible(false);
        try {
            ClassConecta.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(jFDeletaBanco.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizajButtonActionPerformed(null);
        
        if (recebe_controle_botão == 0){
            
            apagaRegistrosBancojButton.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void atualizajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizajButtonActionPerformed
        try {
            // TODO add your handling code here:
            getGradePendentes();
        } catch (ParseException ex) {
            Logger.getLogger(jFDeletaBanco.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        CadastroPendentes oCadastroPendentes = new CadastroPendentes();
//        
//        
//        
//        ResultSet rs = null;
//        ResultSet rs2 = null;
//        ResultSet rs3 = null;
//
//        try {
//            rs = oCadastroPendentes.getContaregistros(conecta);
//            rs2 = oCadastroPendentes.getContaregistrosVencidos(conecta);
//            rs3 = oCadastroPendentes.getContaregistrosNoPrazo(conecta);
//            rs.next();
//            rs2.next();
//            rs3.next();
//            
//            int total_registros = rs.getInt(1);            
//            totalRegistrosjLabel.setText(String.valueOf(total_registros));
//            
//            int total_registros_vencidos = rs2.getInt(1);            
//            totalRegistroVencidojLabel.setText(String.valueOf(total_registros_vencidos));
//            
//            int total_pendentes_no_prazo = rs3.getInt(1);
//            TotalPendentesNoPrazojLabel.setText(String.valueOf(total_pendentes_no_prazo));
//        } catch (Exception e) {
//        }


        
        
        
        
    }//GEN-LAST:event_atualizajButtonActionPerformed

    private void exportaParaExceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportaParaExceljButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser oChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo de excel", "xls");
        oChooser.setFileFilter(filter);
        oChooser.setDialogTitle("Salvar arquivo");
        oChooser.setMultiSelectionEnabled(false);
        oChooser.setAcceptAllFileFilterUsed(false);
        if (oChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
            List<JTable> tb = new ArrayList<>();
            List<String>nom = new ArrayList<>();
            tb.add(gradePendentejTable);
            nom.add("Pendentes Nóhs");
            String file=oChooser.getSelectedFile().toString().concat(".xls");
            try {
                ExportarExcel e = new ExportarExcel(new File(file), tb, nom);
                if (e.exportar()){
                    JOptionPane.showMessageDialog(null, "Os dados foram exportados com sucesso!", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Os dados não foram exportados\n"+e.getMessage(), "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_exportaParaExceljButtonActionPerformed

    private void apagaRegistrosBancojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagaRegistrosBancojButtonActionPerformed
        // TODO add your handling code here:
        
        if (apagaRegistrosBancojButton.isEnabled()){
            
            Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(
                null,
                "Esta ação irá apagar todos os registros do banco de dados.\n Deseja continuar?",
                "Confirmação!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (sd != 0) {
            return;
        }
            CadastroPendentes oCadastroPendentes = new CadastroPendentes();
            oCadastroPendentes.setExcluir(conecta);
            try {
                getGradePendentes();
            } catch (ParseException ex) {
                Logger.getLogger(jFDeletaBanco.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        

        
    }//GEN-LAST:event_apagaRegistrosBancojButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        CadastroPendentes oCadastroPendentes = new CadastroPendentes();
//        
//        
//        
//        ResultSet rs = null;
//        ResultSet rs2 = null;
//        ResultSet rs3 = null;
//
//        try {
//            rs = oCadastroPendentes.getContaregistros(conecta);
//            rs2 = oCadastroPendentes.getContaregistrosVencidos(conecta);
//            rs3 = oCadastroPendentes.getContaregistrosNoPrazo(conecta);
//            rs.next();
//            rs2.next();
//            rs3.next();
//            
//            int total_registros = rs.getInt(1);            
//            totalRegistrosjLabel.setText(String.valueOf(total_registros));
//            
//            int total_registros_vencidos = rs2.getInt(1);            
//            totalRegistroVencidojLabel.setText(String.valueOf(total_registros_vencidos));
//            
//            int total_pendentes_no_prazo = rs3.getInt(1);
//            TotalPendentesNoPrazojLabel.setText(String.valueOf(total_pendentes_no_prazo));
//        } catch (Exception e) {
//        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFDeletaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFDeletaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFDeletaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFDeletaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new jFDeletaBanco().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalPendentesNoPrazojLabel;
    private javax.swing.JButton apagaRegistrosBancojButton;
    private javax.swing.JButton atualizajButton;
    private javax.swing.JButton exportaParaExceljButton;
    private javax.swing.JTable gradePendentejTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton sairjButton;
    private javax.swing.JLabel totalRegistroVencidojLabel;
    private javax.swing.JLabel totalRegistrosjLabel;
    // End of variables declaration//GEN-END:variables
}
